name: simplied_attendace
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  stacked: ^3.4.4
  stacked_services: ^1.6.0
  mobile_scanner: ^7.0.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  stacked_generator: ^1.6.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true